///////////////////////////////////////////////////////////
//  Pausada.cs
//  Implementation of the Class Pausada
//  Generated by Enterprise Architect
//  Created on:      25-May-2014 02:09:14 a.m.
//  Original author: sa
///////////////////////////////////////////////////////////




using Sistema;
namespace Sistema {
	public class Pausada {

		public Pausada(){

		}

		~Pausada(){

		}

		public virtual void Dispose(){

		}

		public Activa cambiarEstado(){

			return null;
		}

	}//end Pausada

}//end namespace Sistema