///////////////////////////////////////////////////////////
//  Publicacion.cs
//  Implementation of the Class Publicacion
//  Generated by Enterprise Architect
//  Created on:      25-May-2014 02:09:18 a.m.
//  Original author: sa
///////////////////////////////////////////////////////////




using Sistema;
using System.Collections.Generic;
using System;
namespace Sistema {
	public class Publicacion {

		public int codigo;
		public string descripcion;
		public int stock;
		public DateTime fechaVenc;
		public DateTime fechInicio;
		public float precio;
		public Rubro rubro;
		public EstadoPublicacion estado;
		public bool aceptaPregunta;
		public VisibilidadPublicacion visibilidadPublicacion;
		public TipoPublicacion tipoPublicacion;
		public bool publicada;
		public List<Pregunta> preguntas;
		public Pregunta m_Pregunta;

		public Publicacion(){

		}

		~Publicacion(){

		}

		public virtual void Dispose(){

		}

		public void modificarPublicacion(){

		}

	}//end Publicacion

}//end namespace Sistema