///////////////////////////////////////////////////////////
//  TipoPublicacion.cs
//  Implementation of the Interface TipoPublicacion
//  Generated by Enterprise Architect
//  Created on:      25-May-2014 02:09:24 a.m.
//  Original author: sa
///////////////////////////////////////////////////////////




using Sistema;
namespace Sistema {
	public interface TipoPublicacion {

	}//end TipoPublicacion

}//end namespace Sistema