///////////////////////////////////////////////////////////
//  VisibilidadPublicacion.cs
//  Implementation of the Class VisibilidadPublicacion
//  Generated by Enterprise Architect
//  Created on:      25-May-2014 02:09:27 a.m.
//  Original author: sa
///////////////////////////////////////////////////////////




using Sistema;
namespace Sistema {
	public class VisibilidadPublicacion {

		private int codigo;
		private string descripcion;
		private float precioPorPublicar;
		private float porcPorVenta;

		public VisibilidadPublicacion(){

		}

		~VisibilidadPublicacion(){

		}

		public virtual void Dispose(){

		}

		public void asignarFecha(){

		}

	}//end VisibilidadPublicacion

}//end namespace Sistema