///////////////////////////////////////////////////////////
//  Borrador.cs
//  Implementation of the Class Borrador
//  Generated by Enterprise Architect
//  Created on:      25-May-2014 02:09:01 a.m.
//  Original author: sa
///////////////////////////////////////////////////////////




using Sistema;
namespace Sistema {
	public class Borrador {

		public Borrador(){

		}

		~Borrador(){

		}

		public virtual void Dispose(){

		}

        public void cambiarEstado()
        {

        }
		/// 
		/// <param name="precio"></param>
		public void cambiarPrecio(double precio){

		}

		/// 
		/// <param name="descripcion"></param>
		public void cambiarDescripcion(string descripcion){

		}

		/// 
		/// <param name="rubro"></param>
		public void cambiarRubro(Rubro rubro){

		}
        /*
		public Activa cambiarEstado(){

			return null;
		}
        */
		/// 
		/// <param name="cambio"></param>
		public void cambiarAceptaPregunta(int cambio){

		}

		public VisibilidadPublicacion cambiarVisibilidadPublicacion(){

			return null;
		}

	}//end Borrador

}//end namespace Sistema