///////////////////////////////////////////////////////////
//  Cliente.cs
//  Implementation of the Class Cliente
//  Generated by Enterprise Architect
//  Created on:      25-May-2014 02:09:05 a.m.
//  Original author: Bruno
///////////////////////////////////////////////////////////




using Sistema;
using System.Collections.Generic;
using System;
namespace Sistema {
	public class Cliente : Usuario {

		public string nombre;
		public string apellido;
		public long numeroDoc;
		public string TipoDeDocumento;
		public string Mail;
		public long Telefono;
		public string Direccion;
        public int numeroCalle;
		public int nroPiso;
		public char depto;
		public string localidad;
		public int codigoPostal;
		public DateTime fechaDeNacimiento;
		public Compra m_Compra;
		public Oferta m_Oferta;
		public List<Publicacion> publicaciones;

		public Cliente(){


		}

		~Cliente(){

		}

		public virtual void Dispose(){

		}

		/// 
		/// <param name="publicacion"></param>
		public Compra comprar(Publicacion publicacion){

			return null;
		}

		/// 
		/// <param name="puntaje"></param>
		public void darPuntaje(int puntaje){

		}

		/// 
		/// <param name="tipoPublicacion"></param>
		/// <param name="visibilidadPublicacion"></param>
		/// <param name="aceptaPregunta"></param>
		/// <param name="rubro"></param>
		/// <param name="precio"></param>
		/// <param name="stock"></param>
		/// <param name="descripcion"></param>
		public Publicacion generarPublicacion(TipoPublicacion tipoPublicacion, VisibilidadPublicacion visibilidadPublicacion, bool aceptaPregunta, Rubro rubro, float precio, int stock, string descripcion){

			return null;
		}

		/// 
		/// <param name="monto"></param>
		public Oferta ofertar(int monto){

			return null;
		}

		public bool Alta(){

			return true;
		}

		public bool Baja(){

			return true;
		}

		public bool Modificacion(){

			return true;
		}

		/// 
		/// <param name="visibilidad"></param>
		/// <param name="compras"></param>
		/// <param name="subastas"></param>
		public Factura rendirFactura(VisibilidadPublicacion visibilidad, List<Compra> compras, List<Subasta> subastas){

			return null;
		}

	}//end Cliente

}//end namespace Sistema