///////////////////////////////////////////////////////////
//  Compra.cs
//  Implementation of the Class Compra
//  Generated by Enterprise Architect
//  Created on:      25-May-2014 02:17:40 p.m.
//  Original author: sa
///////////////////////////////////////////////////////////




using Sistema;
namespace Sistema {
	public class Compra {

		private string fecha;
		private int cantidad;
		private Usuario usuario;
		private int calificacion;

		public Compra(){

		}

		~Compra(){

		}

		public virtual void Dispose(){

		}

	}//end Compra

}//end namespace Sistema