///////////////////////////////////////////////////////////
//  Empresa.cs
//  Implementation of the Class Empresa
//  Generated by Enterprise Architect
//  Created on:      25-May-2014 02:09:08 a.m.
//  Original author: Bruno
///////////////////////////////////////////////////////////




using Sistema;
using System.Collections.Generic;
namespace Sistema {
	public class Empresa : TipoUsuario {

		private string Razonsocial;
		private string Mail;
		private long Telefono;
		private string Direccion;
		private int NroPiso;
		private char Depto;
		private string localidad;
		private int codigoPostal;
		private string ciudad;
		private string CUIT;
		private string nombreDeContacto;
		private string fechaDeCreacion;
		public Publicacion m_Publicacion;

		public Empresa(){

		}

		~Empresa(){

		}

		public virtual void Dispose(){

		}

		/// 
		/// <param name="tipoPublicacion"></param>
		/// <param name="visibilidadPublicacion"></param>
		/// <param name="aceptaPregunta"></param>
		/// <param name="rubro"></param>
		/// <param name="precio"></param>
		/// <param name="stock"></param>
		/// <param name="descripcion"></param>
		public Publicacion generarPublicacion(TipoPublicacion tipoPublicacion, VisibilidadPublicacion visibilidadPublicacion, bool aceptaPregunta, Rubro rubro, float precio, int stock, string descripcion){

			return null;
		}

		public bool Alta(){

			return true;
		}

		public bool Baja(){

			return true;
		}

		public bool Modificacion(){

			return true;
		}

		/// 
		/// <param name="visibilidad"></param>
		/// <param name="compras"></param>
		/// <param name="subastas"></param>
		public Factura rendirFactura(VisibilidadPublicacion visibilidad, List<Compra> compras, List<Subasta> subastas){

			return null;
		}

	}//end Empresa

}//end namespace Sistema