///////////////////////////////////////////////////////////
//  EstadoPublicaion.cs
//  Implementation of the Interface EstadoPublicaion
//  Generated by Enterprise Architect
//  Created on:      25-May-2014 02:09:09 a.m.
//  Original author: sa
///////////////////////////////////////////////////////////




using Sistema;
namespace Sistema {
	public interface EstadoPublicacion {

		void cambiarEstado();
	}//end EstadoPublicaion

}//end namespace Sistema