///////////////////////////////////////////////////////////
//  Finalizada.cs
//  Implementation of the Class Finalizada
//  Generated by Enterprise Architect
//  Created on:      25-May-2014 02:18:02 p.m.
//  Original author: sa
///////////////////////////////////////////////////////////




namespace Sistema {
	public class Finalizada {

		public Finalizada(){

		}

		~Finalizada(){

		}

		public virtual void Dispose(){

		}

        public void cambiarEstado()
        {

        }
	}//end Finalizada

}//end namespace Sistema