///////////////////////////////////////////////////////////
//  Item.cs
//  Implementation of the Class Item
//  Generated by Enterprise Architect
//  Created on:      25-May-2014 02:09:12 a.m.
//  Original author: sa
///////////////////////////////////////////////////////////




namespace Sistema {
	public class Item {

		private float monto;
		private int cantidad;

		public Item(){

		}

		~Item(){

		}

		public virtual void Dispose(){

		}

	}//end Item

}//end namespace Sistema