///////////////////////////////////////////////////////////
//  Oferta.cs
//  Implementation of the Class Oferta
//  Generated by Enterprise Architect
//  Created on:      25-May-2014 02:17:51 p.m.
//  Original author: sa
///////////////////////////////////////////////////////////




using Sistema;
namespace Sistema {
	public class Oferta {

		private string fecha;
		private int monto;
		private Usuario usuario;

		public Oferta(){

		}

		~Oferta(){

		}

		public virtual void Dispose(){

		}

	}//end Oferta

}//end namespace Sistema