///////////////////////////////////////////////////////////
//  Pregunta.cs
//  Implementation of the Class Pregunta
//  Generated by Enterprise Architect
//  Created on:      25-May-2014 02:09:16 a.m.
//  Original author: sa
///////////////////////////////////////////////////////////




namespace Sistema {
	public class Pregunta {

		private string pregunta;
		private string respuesta;

		public Pregunta(){

		}

		~Pregunta(){

		}

		public virtual void Dispose(){

		}

		/// 
		/// <param name="txt"></param>
		public void preguntar(string txt){

		}

		/// 
		/// <param name="txt"></param>
		public void responder(string txt){

		}

	}//end Pregunta

}//end namespace Sistema