///////////////////////////////////////////////////////////
//  Publicacion.cs
//  Implementation of the Class Publicacion
//  Generated by Enterprise Architect
//  Created on:      25-May-2014 02:09:18 a.m.
//  Original author: sa
///////////////////////////////////////////////////////////




using Sistema;
using System.Collections.Generic;
namespace Sistema {
	public class Publicacion {

		private int codigo;
		private string descripcion;
		private int stock;
		private string fechaVenc;
		private string fechInicio;
		private float precio;
		private Rubro rubro;
		private EstadoPublicacion estado;
		private bool aceptaPregunta;
		private VisibilidadPublicacion visibilidadPublicacion;
		private TipoPublicacion tipoPublicacion;
		private bool publicada;
		private List<Pregunta> preguntas;
		public Pregunta m_Pregunta;

		public Publicacion(){

		}

		~Publicacion(){

		}

		public virtual void Dispose(){

		}

		public void modificarPublicacion(){

		}

	}//end Publicacion

}//end namespace Sistema