///////////////////////////////////////////////////////////
//  Rol.cs
//  Implementation of the Class Rol
//  Generated by Enterprise Architect
//  Created on:      25-May-2014 02:09:19 a.m.
//  Original author: sa
///////////////////////////////////////////////////////////




using System.Collections.Generic;
namespace Sistema {
	public class Rol {

        public int idRol;
		private string nombre;
		private List<string> funcionalidades= new List<string>();
        private bool habilitado;

		public Rol(){
            
		}

		~Rol(){

		}

		public virtual void Dispose(){

		}

        public void setNombre(string nombre)
        {
            this.nombre = nombre;
        }

        public string getNombre()
        {
            return this.nombre;
        }

        public void setHabilitado(bool habilitado)
        {
            this.habilitado = habilitado;
        }
        public bool getHabilitado()
        {
            return habilitado;
        }

        public void setFuncionalidades(string funcionalidad)
            {
                funcionalidades.Add(funcionalidad);
            }


        internal bool poseeFuncionalidad(string funcion)
        {
            return funcionalidades.Contains(funcion);
        }

        internal List<string> getListaFuncionalidades()
        {
            return funcionalidades;
        }
    }//end Rol

}//end namespace Sistema