///////////////////////////////////////////////////////////
//  Rubro.cs
//  Implementation of the Class Rubro
//  Generated by Enterprise Architect
//  Created on:      25-May-2014 02:09:20 a.m.
//  Original author: sa
///////////////////////////////////////////////////////////




using Sistema;
namespace Sistema {
	public class Rubro {

		private int codigo;
		private string descripcion;

		public Rubro(){

		}

		~Rubro(){

		}

		public virtual void Dispose(){

		}

	}//end Rubro

}//end namespace Sistema