///////////////////////////////////////////////////////////
//  Usuario.cs
//  Implementation of the Class Usuario
//  Generated by Enterprise Architect
//  Created on:      25-May-2014 02:09:26 a.m.
//  Original author: Bruno
///////////////////////////////////////////////////////////




using Sistema;
namespace Sistema {
	public class Usuario {

        public int usuarioId;
        private string Username;
		private string Password;
		public Rol RolAsignado;
		public bool habilitado;
		public string tipoUsuario;
        public bool cambioContrasenas;
        public bool puedeComprar{get;set;}
        
	
        //public Rol m_Rol;

		public Usuario(){
            this.RolAsignado = new Rol();

		}

        
		~Usuario(){

		}

		public virtual void Dispose(){

		}

        public void setUsuario(string usuario)
        {
            Username=usuario;
        }
        public string getUsuario()
        {
            return this.Username;
        }
        
        public void setPassword(string pass)
        {
            this.Password = pass;
        }

        public string getPassword()
        {
            return Password;
        }

       
        internal bool secambioContrasena()
        {

            return cambioContrasenas;
        }


        internal void cambioContrasena(bool p)
        {
            cambioContrasenas=p;
        }
    }//end Usuario

}//end namespace Sistema