///////////////////////////////////////////////////////////
//  Usuario.cs
//  Implementation of the Class Usuario
//  Generated by Enterprise Architect
//  Created on:      25-May-2014 02:09:26 a.m.
//  Original author: Bruno
///////////////////////////////////////////////////////////




using Sistema;
namespace Sistema {
	public class Usuario {

        private string Username;
		private string Password;
		public Rol RolAsignado;
		public string Tipo;
		public long numero;
		public bool habilitado;
		public TipoUsuario tipoUsuario;
	
        //public Rol m_Rol;

		public Usuario(){

		}

		~Usuario(){

		}

		public virtual void Dispose(){

		}

        public void setUsuario(string usuario)
        {
            Username=usuario;
        }
        public string getUsuario()
        {
            return this.Username;
        }
        
        public void setPassword(string pass)
        {
            this.Password = pass;
        }

        public string getPassword()
        {
            return Password;
        }

	}//end Usuario

}//end namespace Sistema