//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.3655
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrbaCommerce {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Configuracion : global::System.Configuration.ApplicationSettingsBase {
        
        private static Configuracion defaultInstance = ((Configuracion)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Configuracion())));
        
        public static Configuracion Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost\\SQLSERVER2008; initial catalog=GD1C2014 ; User Id=gd ; Pass" +
            "word=gd2014")]
        public string ConexionBase {
            get {
                return ((string)(this["ConexionBase"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2014-12-13")]
        public global::System.DateTime FechaHoy {
            get {
                return ((global::System.DateTime)(this["FechaHoy"]));
            }
        }
    }
}
